# Generated by Django 5.1.3 on 2024-11-23 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_code", models.CharField(max_length=10)),
                ("capacity", models.IntegerField()),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("Lecture Theatre", "Lecture Theatre"),
                            ("Class Room", "Class Room"),
                            ("Lab", "Lab"),
                            ("Seminar Hall", "Seminar Hall"),
                        ],
                        default="Class Room",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("is_hosteller", models.BooleanField(default=False)),
                ("location", models.CharField(max_length=100)),
                ("cgpa", models.DecimalField(decimal_places=2, max_digits=4)),
                ("student_id", models.CharField(max_length=15)),
                ("section", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=100)),
                ("subject_code", models.CharField(max_length=10)),
                ("semester", models.IntegerField()),
                ("credits", models.IntegerField()),
                ("dept", models.CharField(max_length=50)),
                ("course", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=50)),
                ("designation", models.CharField(max_length=50)),
                ("working_days", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TeacherSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.subject",
                    ),
                ),
                (
                    "teacher_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.teacher",
                    ),
                ),
            ],
        ),
    ]
