# Generated by Django 5.1.3 on 2024-11-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("student_id", models.CharField(max_length=15)),
                ("is_hosteller", models.BooleanField(default=False)),
                ("location", models.CharField(max_length=100)),
                ("dept", models.CharField(max_length=50)),
                ("course", models.CharField(max_length=100)),
                ("semester", models.IntegerField()),
                ("section", models.CharField(max_length=2)),
                ("cgpa", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.DeleteModel(
            name="Section",
        ),
    ]
