# Generated by Django 5.1.3 on 2024-11-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_teacher_teacher_code_alter_teacher_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="teacher_code",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
