# Generated by Django 5.1.3 on 2025-02-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0007_alter_teacher_teacher_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="teacher_type",
            field=models.CharField(
                choices=[("admin", "Admin"), ("hod", "HOD"), ("faculty", "Faculty")],
                default="faculty",
                max_length=10,
            ),
        ),
    ]
