# Generated by Django 5.1.3 on 2025-02-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_teacher_password_teacher_teacher_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
