# Generated by Django 5.1.3 on 2025-02-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0015_alter_teacher_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferences", models.JSONField(default=dict)),
            ],
        ),
        migrations.RenameField(
            model_name="student",
            old_name="dept",
            new_name="department",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="dept",
            new_name="department",
        ),
    ]
