# Generated by Django 5.1.3 on 2025-02-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0016_subjectpreference_rename_dept_student_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="is_lab",
            field=models.CharField(default="No", max_length=10),
        ),
        migrations.AddField(
            model_name="teacher",
            name="weekly_workload",
            field=models.IntegerField(default=20),
        ),
    ]
