# Generated by Django 5.1.3 on 2025-02-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0017_subject_is_lab_teacher_weekly_workload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
